### ISSUE TITLE
deploy - heroku.yml

### ISSUE THREAD

**Issue by victorres85** [victorres85/Wine_shop#9]
create the file heroku.yml

codigo utilizado em ultimo projeto:

```
build:
  docker:
    web: dockerfile
run:
  web: gunicorn bookstore01.wsgi:application --bind 0.0.0.0:$PORT
```
